version: '3.9'

services:
  mysql-server:
    image: rubikon23/devopstest:mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123qweAD!
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    ports:
      - '3306:3306'
    restart: always
#    volumes:
#      - ./src/mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']

  zabbix-server:
    image: rubikon23/devopstest:zbxserver
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    ports:
       - '10051:10051'
    restart: always
    links:
      - mysql-server
    depends_on:
      - mysql-server

  zabbix-web:
    image: rubikon23/devopstest:zbxweb
    container_name: zabbix-web1
    environment:
      MYSQL_ROOT_PASSWORD: 123qweAD!
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      DB_SERVER_HOST: mysql-server
      DB_SERVER_PORT: 3306
      PHP_TZ: Europe/Moscow
    ports:
      - '80:80'
      - '443:443'
      - '8443:8443'
      - '8080:8080'
    restart: always
    links:
      - zabbix-server
    depends_on:
      - zabbix-server
  web:
    image: rubikon23/devopstest:flask
    ports:
      - "5000:5000"
